### ISSUE TITLE
[Feat] 커뮤니티 구현

### ISSUE THREAD

**Issue by seohyeon121** [Fill-ENERGY/Android#4]
## Issue

이슈 내용: 커뮤니티 기능 구현

## Branch Name

 생성 브랜치 이름 : Feature/#4-community

## To-Do List

- [x] 상단 카테고리 별 view 구현
- [x] 게시글 업로드 기능
- [ ] 이미지 업로드 기능
- [ ] 키워드 검색 기능
- [x] 댓글 기능
- [x] 좋아요 기능
- [x] 비밀댓글 기능 (후순위)
